# -----------------------------
# The Site Configuration
# -----------------------------

theme: jekyll-theme-chirpy
lang: ko-KR
timezone: Asia/Seoul

# -----------------------------
# 기본 정보 (필수)
# -----------------------------
title: "KingBlackCow's Dev Blog"
tagline: "Backend Developer / AWS / Kafka / Elixir"
description: >-
  백엔드 개발자로서의 기술 기록과 인사이트를 공유합니다.

url: "https://KingBlackCow.github.io"

# -----------------------------
# 소셜 및 저자 정보
# -----------------------------
github:
  username: KingBlackCow

social:
  name: "JS LEE"
  email: "your_email@example.com"
  links:
    - https://github.com/KingBlackCow
    # 필요하면 더 추가 가능
    # - https://linkedin.com/in/yourname
    # - https://twitter.com/yourname

# -----------------------------
# 기타 설정
# -----------------------------
theme_mode: dark   # 기본 다크모드
cdn: "https://chirpy-img.netlify.app"
avatar: "/commons/avatar.jpg"
social_preview_image: # 필요 시 이미지 URL 넣기
toc: true

# 댓글 설정 (원하면 Giscus 나중에 연결)
comments:
  provider: giscus
  giscus:
    repo: KingBlackCow/KingBlackCow.github.io
    repo_id: ""
    category: "General"
    category_id: ""
    mapping: pathname
    reactions_enabled: 1

# -----------------------------
# Web Analytics (선택)
# -----------------------------
analytics:
  google:
    id: "" # 나중에 Google Analytics 코드 넣기

# -----------------------------
# 기타 기본값 (그대로 유지)
# -----------------------------
paginate: 10
baseurl: ""

pwa:
  enabled: true
  cache:
    enabled: true